ignored:
  - DL3008 # Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
  - DL3059 # Multiple consecutive `RUN` instructions. Consider consolidation.
  - DL4006 # Set the SHELL option -o pipefail before RUN with a pipe in it.
