name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            .apt/cache
            .apt/state
          key: ${{ runner.os }}-apt
      - run: ./.apt/get.sh update
      - run: ./.apt/get.sh install --download-only google-chrome-stable
      - run: sudo ./.apt/get.sh install google-chrome-stable

      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: npm
      - run: npm ci
      - run: npm run test:ci
